//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.10 at 12:16:15 PM PKT 
//


package soapapiss.practice.soapapi.com;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emplooyInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emplooyInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="emplooyesId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="emplooyesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emplooyesSallery" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emplooyInfo", propOrder = {
    "emplooyesId",
    "emplooyesName",
    "emplooyesSallery"
})
public class EmplooyInfo {

    protected long emplooyesId;
    @XmlElement(required = true)
    protected String emplooyesName;
    protected long emplooyesSallery;

    /**
     * Gets the value of the emplooyesId property.
     * 
     */
    public long getEmplooyesId() {
        return emplooyesId;
    }

    /**
     * Sets the value of the emplooyesId property.
     * 
     */
    public void setEmplooyesId(long value) {
        this.emplooyesId = value;
    }

    /**
     * Gets the value of the emplooyesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplooyesName() {
        return emplooyesName;
    }

    /**
     * Sets the value of the emplooyesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplooyesName(String value) {
        this.emplooyesName = value;
    }

    /**
     * Gets the value of the emplooyesSallery property.
     * 
     */
    public long getEmplooyesSallery() {
        return emplooyesSallery;
    }

    /**
     * Sets the value of the emplooyesSallery property.
     * 
     */
    public void setEmplooyesSallery(long value) {
        this.emplooyesSallery = value;
    }

}
