//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.10 at 12:16:15 PM PKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.soapApi.practice.SoapApiss", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soapapiss.practice.soapapi.com;
